services:
  tempo.knight.api:
    image: ${DOCKER_REGISTRY-}tempo-knights-api
    build:
      context: .
      dockerfile: Tempo.Knight.Api/Dockerfile
    ports:
       - "9000:9000"     
       - "9001:9001"
    environment:
      - ASPNETCORE_URLS=http://+:9000
      - ASPNETCORE_URLS=https://+:9001
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - TempoKnights_default
  
networks:
  TempoKnights_default:
    driver: bridge
